version: '3.7'

networks:
  we5net:

volumes:
  mysql:

services:
  mariadb:
    env_file:
      - default.env
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      we5net:

  frontend:
    env_file:
      - default.env
    build:
      context: ./frontendWe5
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "80:80"
    networks:
      we5net:

  backend:
    env_file:
      - default.env
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: run
    ports:
      - "8084:8084"
    networks:
      we5net: