export enum Role{
    ROLE_RECHENZENTRUM="ROLE_RECHENZENTRUM", 
    ROLE_HAUSVERWALTUNG="ROLE_HAUSVERWALTUNG", 
    ROLE_MEDIENTECHNIK="ROLE_MEDIENTECHNIK", 
    ROLE_REINIGUNGSFIRMA="ROLE_REINIGUNGSFIRMA", 
    ROLE_REPORTER="ROLE_REPORTER", 
    ROLE_ADMIN="ROLE_ADMIN"
}